// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               unknown

/* eslint-disable */

export * as v1 from "./index.tides.sui.common.v1";
