// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               unknown

/* eslint-disable */

export * as protobuf from "./index.google.protobuf";
